"""ats_scans

Revision ID: 25bc41b12c0e
Revises: 30184cc9c095
Create Date: 2026-08-12 16:03:41.493759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bc41b12c0e'
down_revision: Union[str, Sequence[str], None] = '30184cc9c095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ats_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['generated_docs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ats_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ats_scans_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ats_scans_resume_id'), ['resume_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ats_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ats_scans_resume_id'))
        batch_op.drop_index(batch_op.f('ix_ats_scans_doc_id'))

    op.drop_table('ats_scans')
    # ### end Alembic commands ###
