"""tex_source nullable for pdf-only resumes

Revision ID: 7d456894ebed
Revises: 4a12bb52f2ca
Create Date: 2026-07-27 19:53:18.832871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d456894ebed'
down_revision: Union[str, Sequence[str], None] = '4a12bb52f2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.alter_column('tex_source',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.alter_column('tex_source',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
