"""voice tables + doc body columns

Revision ID: 9666d74afcb0
Revises: f1c39d8a678e
Create Date: 2026-07-28 18:32:15.127577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9666d74afcb0'
down_revision: Union[str, Sequence[str], None] = 'f1c39d8a678e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('learned_rules', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_docs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('body_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_docs', schema=None) as batch_op:
        batch_op.drop_column('body_text')
        batch_op.drop_column('draft_text')

    op.drop_table('voice_samples')
    op.drop_table('style_profiles')
    # ### end Alembic commands ###
