"""prep_sessions

Revision ID: 9760962f2f8f
Revises: 25bc41b12c0e
Create Date: 2026-08-13 05:12:08.645810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9760962f2f8f'
down_revision: Union[str, Sequence[str], None] = '25bc41b12c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prep_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('transcript', sa.JSON(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prep_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prep_sessions_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prep_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prep_sessions_job_id'))

    op.drop_table('prep_sessions')
    # ### end Alembic commands ###
