"""profile_fields

Revision ID: a453c0ad5d33
Revises: 7d456894ebed
Create Date: 2026-07-27 21:06:40.466004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a453c0ad5d33'
down_revision: Union[str, Sequence[str], None] = '7d456894ebed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_fields_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_fields_key'))

    op.drop_table('profile_fields')
    # ### end Alembic commands ###
