"""network targets + people

Revision ID: c801da540a2f
Revises: d3c673ef215d
Create Date: 2026-07-31 10:21:18.645554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c801da540a2f'
down_revision: Union[str, Sequence[str], None] = 'd3c673ef215d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('role_type', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_targets_company'), ['company'], unique=False)

    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('person_type', sa.String(length=20), nullable=False),
    sa.Column('profile_url', sa.String(length=1000), nullable=True),
    sa.Column('evidence_urls', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('match_signals', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('connection_note', sa.Text(), nullable=True),
    sa.Column('followup', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_status'))
        batch_op.drop_index(batch_op.f('ix_people_company'))

    op.drop_table('people')
    with op.batch_alter_table('network_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_targets_company'))

    op.drop_table('network_targets')
    # ### end Alembic commands ###
