"""vetted flag + apply sessions

Revision ID: d3c673ef215d
Revises: 9666d74afcb0
Create Date: 2026-07-29 05:29:03.514420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c673ef215d'
down_revision: Union[str, Sequence[str], None] = '9666d74afcb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('resume_doc_id', sa.Integer(), nullable=True),
    sa.Column('cover_doc_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cover_doc_id'], ['generated_docs.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_doc_id'], ['generated_docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_docs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vetted', sa.Boolean(), nullable=False, server_default=sa.text("0")))

    op.execute(
        "UPDATE generated_docs SET vetted = 1 WHERE doc_type = 'cover_letter' AND approved = 1"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_docs', schema=None) as batch_op:
        batch_op.drop_column('vetted')

    op.drop_table('apply_sessions')
    # ### end Alembic commands ###
