"""memory muted + doc divergence

Revision ID: f1c39d8a678e
Revises: a453c0ad5d33
Create Date: 2026-07-28 07:37:20.505416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c39d8a678e'
down_revision: Union[str, Sequence[str], None] = 'a453c0ad5d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_docs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('divergence', sa.Float(), nullable=True))

    with op.batch_alter_table('memory_entries', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('muted', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_entries', schema=None) as batch_op:
        batch_op.drop_column('muted')

    with op.batch_alter_table('generated_docs', schema=None) as batch_op:
        batch_op.drop_column('divergence')

    # ### end Alembic commands ###
